<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.Abstractions" Version="30.0.1-mike.0.ci.1" />
    <PackageReference Include="CK.ActivityMonitor.SimpleSender" Version="27.0.1-mike.0.ci.3" />
    <PackageReference Include="CK.PerfectEvent" Version="28.0.1-mike.0.ci.1" />
  </ItemGroup>
</Project>