using CK.Core;

namespace CK.Globalization;

/// <summary>
/// Real-object carrier whose <see cref="ApplyTranslations"/> body is generated by the CK.Globalization.Engine
/// aspect to register merged per-package <c>Res/locales</c> translations. Its <c>RegisterStartupServices</c> runs
/// at the top of the DI-configuration phase (after all <c>StObjInitialize</c>, before the service provider is built):
/// early enough since the translation cache is a process-global static read only at message-format time.
/// A no-op when the engine generates an empty body.
/// </summary>
public abstract class GlobalizationTranslationInstaller : IRealObject
{
    // RegisterStartupServices (rather than StObjInitialize) is used so this carrier depends only on CK.Core
    // (SimpleServiceContainer) and NOT on CK.StObj.Model (IStObjObjectMap): the latter pulls CK.Engine.Configuration
    // and would create a repository cycle (CK.StObj.Runtime references CK.Globalization). The 'services' parameter
    // is unused — the hook exists only to trigger the engine-generated ApplyTranslations override.
    void RegisterStartupServices( IActivityMonitor monitor, SimpleServiceContainer services ) => ApplyTranslations();

    /// <summary>
    /// Generated as an <c>override</c> in the <c>_CK</c> class by the CK.Globalization.Engine aspect.
    /// Declared <c>virtual</c> with an empty body (rather than <c>abstract</c> + <c>[AutoImplementationClaim]</c>)
    /// so the carrier is auto-discoverable and compiles cleanly even in a build that references CK.Globalization
    /// but NOT CK.Globalization.Engine (e.g. an empty engine configuration): the abstract member would otherwise
    /// be left uncovered and fail code generation (CS0534).
    /// </summary>
    protected virtual void ApplyTranslations() { }
}
